#!/usr/bin/env python3
"""
Analyze the structure of HSK1 textbook chapters using Claude.
This script reads the OCR output and asks Claude to identify the consistent structure
across all chapters, accounting for OCR errors.
"""

import os
import sys
from pathlib import Path

# Load .env from repo root
def load_env():
    env_path = Path(__file__).parent.parent / ".env"
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key] = value

load_env()

try:
    import anthropic
except ImportError:
    print("Installing anthropic package...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "anthropic", "-q"])
    import anthropic


def read_hsk1_content():
    """Read the raw OCR content."""
    script_dir = Path(__file__).parent
    # Use raw OCR file for structure analysis
    ocr_path = script_dir / "hsk1_ocr.txt"
    if not ocr_path.exists():
        ocr_path = script_dir / "hsk1.txt"
    
    with open(ocr_path, 'r', encoding='utf-8') as f:
        return f.read()


def analyze_structure_with_claude(content: str) -> str:
    """Use Claude to analyze the chapter structure."""
    
    client = anthropic.Anthropic()
    
    prompt = f"""You are analyzing a Chinese language textbook (HSK 1, Chapters 1-15) that was extracted via OCR from a scanned PDF.

The OCR has introduced errors that you need to be aware of:
- Pinyin may be garbled (e.g., "bu shi" might appear as "bi shi", "hǎo" as "hdo")
- Numbers in pinyin tone marks may be missing or wrong
- English text has typos (e.g., "Hello" as "Hcllo", "good" as "go0d")
- Chinese characters are generally accurate

Your task: Analyze this content and identify the CONSISTENT STRUCTURE that each chapter/lesson follows.

HSK textbooks typically have sections like:
- Warm-up / 热身 (beginning of lesson)
- Text/Dialogue / 课文 (main dialogues)
- New Words / 生词 (vocabulary lists)
- Pinyin / 拼音 (pronunciation notes)
- Grammar / 语法 (grammar explanations)
- Characters / 汉字 (character writing)
- Exercises / 练习 (practice activities)

Please analyze the content below and provide:

1. **CHAPTER STRUCTURE TEMPLATE**: A detailed template showing the exact sections that appear in each chapter, in order. Include both Chinese and English names where visible.

2. **SECTION MARKERS**: The exact text patterns (accounting for OCR variations) that indicate each section begins.

3. **CONTENT FORMAT**: For each section, describe:
   - What type of content it contains
   - How vocabulary entries are formatted (Chinese | pinyin | English? Or different?)
   - How dialogues are formatted (speaker labels, audio markers like "01-1", etc.)

4. **OCR CORRECTION RULES**: Common OCR errors you noticed and how to fix them:
   - Pinyin patterns that need correction
   - Common character substitutions
   - Formatting issues

5. **SUGGESTED JSON SCHEMA**: Propose a JSON structure that could represent a clean, corrected chapter.

Here is the OCR content to analyze:

---
{content[:80000]}
---

Please be thorough and specific. This analysis will be used to write a second prompt that corrects each chapter individually."""

    print("Sending content to Claude for structure analysis...")
    print(f"Content length: {len(content)} chars (sending first 80k)")
    
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=8000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    
    return response.content[0].text


def main():
    script_dir = Path(__file__).parent
    output_path = script_dir / "chapter_structure_analysis.txt"
    
    print("Reading HSK1 OCR content...")
    content = read_hsk1_content()
    print(f"Read {len(content)} characters")
    
    print("\nAnalyzing structure with Claude...")
    analysis = analyze_structure_with_claude(content)
    
    # Save the analysis
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# HSK1 Chapter Structure Analysis\n")
        f.write("# Generated by Claude from OCR content\n")
        f.write("# Use this to guide chapter-by-chapter correction\n\n")
        f.write(analysis)
    
    print(f"\n{'='*60}")
    print("STRUCTURE ANALYSIS")
    print('='*60)
    print(analysis)
    print(f"\n{'='*60}")
    print(f"Analysis saved to: {output_path}")


if __name__ == "__main__":
    main()
